# Generated by Django 4.1 on 2023-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('brief_description', models.CharField(max_length=50)),
                ('first_paragraph', models.CharField(max_length=100)),
                ('second_paragraph', models.CharField(max_length=100)),
                ('third_paragraph', models.CharField(max_length=100)),
                ('question_one', models.CharField(max_length=50)),
                ('question_two', models.CharField(max_length=50)),
                ('question_three', models.CharField(max_length=50)),
                ('answer_one', models.CharField(max_length=200)),
                ('answer_two', models.CharField(max_length=200)),
                ('answer_three', models.CharField(max_length=200)),
                ('condition_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Dermatologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('brief_information', models.CharField(max_length=50)),
                ('profile_information', models.CharField(max_length=1000)),
                ('scientific_degree', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='General_Health_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('brief_information', models.CharField(max_length=50)),
                ('profile_information', models.CharField(max_length=1000)),
                ('scientific_degree', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gynecologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('brief_information', models.CharField(max_length=50)),
                ('profile_information', models.CharField(max_length=1000)),
                ('scientific_degree', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Naturopathist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('brief_information', models.CharField(max_length=50)),
                ('profile_information', models.CharField(max_length=1000)),
                ('scientific_degree', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Psychiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('brief_information', models.CharField(max_length=50)),
                ('profile_information', models.CharField(max_length=1000)),
                ('scientific_degree', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
