# Generated by Django 4.1 on 2023-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('patient_first_name', models.CharField(max_length=30)),
                ('patient_last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('speciality_field', models.CharField(max_length=30)),
                ('condition_field', models.CharField(max_length=30)),
            ],
        ),
    ]
