# Generated by Django 4.1 on 2023-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brief_description', models.CharField(max_length=100)),
                ('first_paragraph', models.CharField(max_length=100)),
                ('second_paragraph', models.CharField(max_length=100)),
                ('third_paragraph', models.CharField(max_length=100)),
                ('question_one', models.CharField(max_length=50)),
                ('question_two', models.CharField(max_length=50)),
                ('question_three', models.CharField(max_length=50)),
                ('answer_one', models.CharField(max_length=200)),
                ('answer_two', models.CharField(max_length=200)),
                ('answer_three', models.CharField(max_length=200)),
                ('blog_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
