# Generated by Django 4.1 on 2023-12-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='answer_one',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blog',
            name='answer_three',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blog',
            name='answer_two',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blog',
            name='first_paragraph',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='second_paragraph',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='third_paragraph',
            field=models.CharField(max_length=500),
        ),
    ]
